# Generated by Django 3.2 on 2021-06-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200)),
                ('prod_type', models.CharField(max_length=200)),
                ('prod_about', models.CharField(max_length=200)),
            ],
        ),
    ]
